[package]
name = "epub-audiobook-studio"
version = "1.0.0"
description = "Xuong Sach Noi desktop shell"
authors = ["EPUB Audiobook Studio"]
edition = "2021"

[lib]
name = "epub_audiobook_studio_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
