import React, { useEffect, useState } from "react";
import { AudioLines, Plus, Trash2, Pencil, RefreshCw } from "lucide-react";
import { api, postForm, postJson, EffectItem } from "@/api";
import { Header, LoadingState, EmptyState } from "@/components/common/Header";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";

export function EffectsPage() {
  const [items, setItems] = useState<EffectItem[]>([]); const [loading, setLoading] = useState(true); const [marker, setMarker] = useState(""); const [description, setDescription] = useState(""); const [file, setFile] = useState<File | null>(null); const [edit, setEdit] = useState<EffectItem | null>(null);
  const load = () => { setLoading(true); api<{ effects: EffectItem[] }>("/effects/list").then((x) => setItems(x.effects || [])).finally(() => setLoading(false)); };
  useEffect(load, []);
  const add = async (e: React.FormEvent) => { e.preventDefault(); if (!file) return; const form = new FormData(); form.append("marker", marker); form.append("description", description); form.append("file", file); try { await postForm("/effects/add", form); setMarker(""); setDescription(""); setFile(null); load(); } catch (err: any) { alert(err.message); } };
  const remove = async (id: number) => { if (!confirm("Xóa hiệu ứng này?")) return; try { await postForm(`/effects/${id}/delete`, new FormData()); load(); } catch (e: any) { alert(e.message); } };
  const save = async () => { if (!edit) return; try { await postJson(`/effects/${edit.id}/edit`, { marker: edit.marker, description: edit.description }); setEdit(null); load(); } catch (e: any) { alert(e.message); } };
  if (loading) return <LoadingState text="Đang tải thư viện hiệu ứng..." />;
  return <div className="space-y-6"><Header title="Thư viện hiệu ứng âm thanh" subtitle="Quản lý marker hiệu ứng dùng trong các patch audiobook." action={<Button variant="outline" size="sm" onClick={load}><RefreshCw className="h-4 w-4" /> Làm mới</Button>} /><Card><CardHeader><CardTitle className="text-sm flex items-center gap-2"><Plus className="h-4 w-4 text-primary" /> Thêm hiệu ứng</CardTitle></CardHeader><CardContent><form onSubmit={add} className="grid grid-cols-1 md:grid-cols-4 gap-3"><Input placeholder="Marker, ví dụ [door]" value={marker} onChange={(e) => setMarker(e.target.value)} required /><Input placeholder="Mô tả" value={description} onChange={(e) => setDescription(e.target.value)} /><Input type="file" accept="audio/*" onChange={(e) => setFile(e.target.files?.[0] || null)} required /><Button type="submit"><Plus className="h-4 w-4" /> Thêm</Button></form></CardContent></Card>{items.length === 0 ? <EmptyState text="Chưa có hiệu ứng nào." /> : <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{items.map((item) => <Card key={item.id}><CardHeader className="p-4 pb-2"><CardTitle className="text-sm flex items-center justify-between"><span className="flex items-center gap-2"><AudioLines className="h-4 w-4 text-primary" />{item.marker}</span><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={() => setEdit(item)}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" className="text-destructive" onClick={() => remove(item.id)}><Trash2 className="h-4 w-4" /></Button></div></CardTitle></CardHeader><CardContent className="p-4 pt-1 space-y-2"><audio controls className="w-full" src={`/effects/${item.id}/audio`} /><p className="text-xs text-muted-foreground">{item.description || "Chưa có mô tả"}</p></CardContent></Card>)}</div>}<Dialog open={!!edit} onOpenChange={(v) => !v && setEdit(null)}><DialogContent><DialogHeader><DialogTitle>Sửa hiệu ứng</DialogTitle></DialogHeader>{edit && <div className="space-y-3"><Input value={edit.marker} onChange={(e) => setEdit({ ...edit, marker: e.target.value })} /><Input value={edit.description} onChange={(e) => setEdit({ ...edit, description: e.target.value })} /></div>}<DialogFooter><Button variant="outline" onClick={() => setEdit(null)}>Hủy</Button><Button onClick={save}>Lưu</Button></DialogFooter></DialogContent></Dialog></div>;
}
