import React, { useEffect, useState } from "react";
import { Workflow, Plus, Play, RefreshCw } from "lucide-react";
import { api, postJson, FlowDefinition } from "@/api";
import { Header, LoadingState, EmptyState } from "@/components/common/Header";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function FlowsPage() {
  const [flows, setFlows] = useState<FlowDefinition[]>([]); const [books, setBooks] = useState<any[]>([]); const [patches, setPatches] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [name, setName] = useState(""); const [nodes, setNodes] = useState<string[]>(["audio", "video", "youtube"]); const [bookId, setBookId] = useState(""); const [selectedPatches, setSelectedPatches] = useState<number[]>([]); const [privacy, setPrivacy] = useState("private");
  const load = () => { setLoading(true); Promise.all([api<{ flows: FlowDefinition[] }>("/flows/api"), api<any>("/api/ui/books?per_page=100")]).then(([f, b]) => { setFlows(f.flows || []); setBooks(b.items || []); }).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  useEffect(() => { if (bookId) api<any>(`/flows/1/patches?book_id=${bookId}`).then((x) => setPatches(x.patches || [])).catch(() => setPatches([])); }, [bookId]);
  const create = async () => { if (!name.trim()) return; try { await postJson("/flows/api", { name, nodes }); setName(""); load(); } catch (e: any) { alert(e.message); } };
  const run = async (flow: FlowDefinition) => { if (!bookId || selectedPatches.length === 0) return alert("Chọn sách và ít nhất một patch"); try { const r = await postJson<any>(`/flows/${flow.id}/runs`, { book_id: Number(bookId), patch_ids: selectedPatches, privacy }); alert(`Đã tạo run #${r.run_id} với ${r.job_count} job.`); } catch (e: any) { alert(e.message); } };
  if (loading) return <LoadingState text="Đang tải các flow..." />;
  return <div className="space-y-6"><Header title="Luồng sản xuất (Flows)" subtitle="Tạo chuỗi xử lý audio, video và YouTube theo đúng node backend." action={<Button variant="outline" size="sm" onClick={load}><RefreshCw className="h-4 w-4" /> Làm mới</Button>} /><Card><CardHeader><CardTitle className="text-sm flex items-center gap-2"><Plus className="h-4 w-4 text-primary" /> Tạo flow mới</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex gap-2"><Input placeholder="Tên flow" value={name} onChange={(e) => setName(e.target.value)} /><Button onClick={create}>Tạo flow</Button></div><div className="flex flex-wrap gap-3 text-xs">{["audio", "video", "youtube"].map((node) => <label key={node} className="flex items-center gap-2"><input type="checkbox" checked={nodes.includes(node)} onChange={(e) => setNodes((p) => e.target.checked ? [...p, node] : p.filter((x) => x !== node))} />{node}</label>)}</div></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Chọn book / patch để chạy flow</CardTitle></CardHeader><CardContent className="grid grid-cols-1 md:grid-cols-3 gap-3"><select className="h-9 rounded-md border border-input bg-background px-3 text-sm" value={bookId} onChange={(e) => setBookId(e.target.value)}><option value="">-- Chọn sách --</option>{books.map((b) => <option key={b.id} value={b.id}>{b.title}</option>)}</select><select multiple className="h-24 rounded-md border border-input bg-background px-3 text-sm" value={selectedPatches.map(String)} onChange={(e) => setSelectedPatches(Array.from(e.target.selectedOptions).map((o) => Number(o.value)))}>{patches.map((p) => <option key={p.id} value={p.id}>#{p.index} {p.name} · {p.status}</option>)}</select><select className="h-9 rounded-md border border-input bg-background px-3 text-sm" value={privacy} onChange={(e) => setPrivacy(e.target.value)}><option value="private">Private</option><option value="unlisted">Unlisted</option><option value="public">Public</option></select></CardContent></Card>{flows.length === 0 ? <EmptyState text="Chưa có flow nào." /> : <div className="grid grid-cols-1 md:grid-cols-2 gap-4">{flows.map((flow) => <Card key={flow.id}><CardHeader className="p-4 pb-2"><CardTitle className="text-sm flex items-center gap-2"><Workflow className="h-4 w-4 text-primary" />{flow.name}</CardTitle></CardHeader><CardContent className="p-4 pt-2 flex items-center justify-between"><div className="flex gap-1">{flow.nodes.map((n) => <span key={n} className="text-[10px] font-mono rounded bg-muted px-2 py-1">{n}</span>)}</div><Button size="sm" onClick={() => run(flow)}><Play className="h-3.5 w-3.5" /> Chạy</Button></CardContent></Card>)}</div>}</div>;
}
